import Footer from 'components/navigation/footer/Footer';
import { Providers } from '../Redux/provider';
import '../styles/globals.css';
import Header from './Header';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-200 ">
          <Providers>
            <Header />
            {children}
            <div className="m-auto" />
          </Providers>
        </div>
        <Footer />
      </body>
    </html>
  );
}
